# Default configuration for the market-hub

[app]
app_env = "product"
pool_txt = "./pool_addresses.txt"
folder_snapshot = ""
folder_dump = "./dumps"
to_block = 27970848
block_step = 1000
num_threads = 1
log_fetch_concurrency = 10
rpc_batch_size = 10

[rpc]
http = ["http://92.53.84.169:8545/"]

[bsc_scan]
api_key = ""